version: '3.1'

services:
  p2p-crawler:
    env_file:
      - ../configs/.env
    build:
      context: ../
      dockerfile: build/Dockerfile
    volumes:
      - "../db:/go/src/crawler/db"
    image: crawler:latest
