version: '3.1'

services:
  p2p-crawler:
    env_file:
      - configs/.env
    build:
      context: .
      dockerfile: build/Dockerfile
    image: crawler:latest
    network_mode: "host"
    command: [ "/go/src/crawler/scripts/wait-for-it.sh", "localhost:3306", "--timeout=30", "--", "/go/src/crawler/bin/p2pcrawler" ]